theme = "gruvbox"


[editor]
auto-format = false
line-number = "relative"
completion-trigger-len = 1
mouse = false
idle-timeout = 0
gutters = ["line-numbers"]

[keys.normal]
"tab" = "rotate_view"
"ret" = ["open_below", "normal_mode"]

[editor.lsp]
display-messages = true
auto-signature-help = false

[editor.indent-guides]
render = false
