theme = "gruvbox"


[editor]
auto-format = false
line-number = "absolute"
completion-trigger-len = 1
mouse = false
idle-timeout = 0
gutters = ["line-numbers"]

[keys.normal]
"tab" = "rotate_view"
"ret" = ["open_below", "normal_mode"]
"S-ret" = ["open_above", "normal_mode"]
"A-y" = "switch_to_uppercase"
"A-h" = "switch_to_lowercase"
# "A-a" = [""]

[editor.lsp]
display-messages = true
auto-signature-help = false

[editor.indent-guides]
render = false
